[package]
name = "ccc-rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
actix-web = { version = "4", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
